import Head from 'next/head'
import styles from '../styles/Home.module.css'

type Item = {
  title: string
  original_url: string,
  affliate_url: string,
  original_price: number,
  discounted_price: number,
  image_url: string,
  rating: {
    total_count: number,
    avg_rating:number,
    ratings:{},
  }
}

type KeywordData = {
  keyword: string,
  pre_render: boolean,
  recommended_item:Item
  searched_items: [Item],
}

export default function DetailPage({keywordData} : {
  keywordData: KeywordData
}) {
  return (
    <>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing
          </p>
        </div>
      </main>
    </>
  )
}

